config/routes.rb
Rails.application.routes.draw do
  get 'notes', to: 'notes#index'
  post 'notes', to: 'notes#create'
  get 'notes/new', to: 'notes#new', as: :new_note
  get 'notes/:id', to: 'notes#show', as: :note
  patch 'notes/:id', to: 'notes#update'
  delete 'notes/:id', to: 'notes#destroy'
  get 'notes/:id/edit', to: 'notes#edit', as: :edit_note

  get 'items', to: 'items#index'
  post 'items', to: 'items#create'
  get 'items/new', to: 'items#new', as: :new_item
  get 'items/:id/edit', to: 'items#edit', as: :edit_item
  patch 'items/:id', to: 'items#update', as: :item
  delete 'items/:id', to: 'items#destroy'

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, length: { minimum: 3 }
  validates :expected_cost, comparison: { less_than: 50 }
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { in: 5..12 }
  validates :body, presence: true
end

app/models/user.rb
class User
  attr_reader :name, :hobbies, :info
  
  def initialize(name:, hobbies: [], info: {})
    @name = name
    @hobbies = hobbies
    @info = info
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.delete
  
    redirect_to @item
  end

  private

  def item_params
    params.require(:item).permit(:title, :expected_cost, :is_done)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all
  end

  def show
  end
  
  def new
    @note = Note.new
  end
  
  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note.delete

    redirect_to notes_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @user = User.new(
      name: "Peter the Great",
      hobbies: ["kingdom", "hunting", "conquering"],
      info: { age: 55, height: 180 }
    )
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, class: 'grid grid-cols-1 sm:grid-cols-6 max-w-3xl gap-x-6 gap-y-8' do |f| %>
  <% if @item.errors.any? %>
    <ul class='mt-4 bg-rose-100 border border-rose-400 rounded-md p-3 col-span-full list-disc list-inside'>
      <% @item.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class='sm:col-span-5'>
    <%= f.label :title, class: 'text-sm' %>
    <%= f.text_field :title, class: 'w-full mt-2 block border-0 ring-1 ring-gray-200 rounded-md' %>
  </div>
  <div class='sm:col-span-2'>
    <%= f.label :expected_cost, class: 'text-sm' %>
    <%= f.number_field :expected_cost, class: 'w-full mt-2 block border-0 ring-1 ring-gray-200 rounded-md' %>
  </div>
  <div class='col-span-full'>
    <%= f.submit class: 'px-3 py-1.5 bg-indigo-600 text-white rounded-md' %>
    <%= link_to 'Cancel', cancel_path, class: 'ml-4' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back to item', @item %>

app/views/items/index.html.erb
<header>
  <%= link_to root_path, class: 'text-gray-400' do %>
    &larr; Home
  <% end %>
  <div class='flex justify-between items-center'>
    <h1 class='text-2xl font-bold'>Items</h1>
    <%= link_to 'New Item', new_item_path, class: 'inline-block px-3 py-1.5 bg-indigo-600 rounded-md text-white' %>
  </div>
</header>

<section class='grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-6 mt-6 gap-x-6 gap-y-8'>
  <% @items.each do |item| %>
    <% if item.is_done? %>
      <%= button_to item, method: :delete, class: 'w-full text-left p-4 shadow-lg bg-emerald-50 rounded-md' do %>
        <h1 class='text-xl'><%= item.title %></h1>
        <%= number_to_currency item.expected_cost, unit: '€', format: "%n %u" %>
      <% end %>
    <% else %>
      <%= button_to item, method: :patch, params: { item: { is_done: true } }, class: 'w-full text-left p-4 shadow-lg bg-stone-50 rounded-md' do %>
        <h1 class='text-xl'><%= item.title %></h1>
        <%= number_to_currency item.expected_cost, unit: '€', format: "%n %u" %>
      <% end %>
    <% end %>
  <% end %>
</section>

<!--<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>What to buy?</th>
      <th>Expected cost</th>
      <th>Done?</th>
      <th colspan='2'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.title, item %></td>
        <td><%= item.expected_cost %></td>
        <td><%= item.is_done %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= button_to 'Delete', item, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

app/views/items/new.html.erb
<h1 class='text-2xl font-bold'>New item</h1>

<%= render 'form', cancel_path: items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: @note, class: 'grid grid-cols-1 sm:grid-cols-6 max-w-3xl gap-y-8' do |f| %>
  <% if @note.errors.any? %>
    <ul class='bg-rose-100 border border-rose-400 rounded-md p-3 col-span-4 list-disc list-inside'>
      <% @note.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class='sm:col-span-4'>
    <%= f.label :title, class: 'text-sm' %>
    <%= f.text_field :title, class: 'w-full mt-2 block border-0 ring-1 ring-gray-200 rounded-md' %>
  </div>
  <div class='col-span-full'>
    <%= f.label :body, class: 'text-sm' %>
    <%= f.text_area :body, class: 'w-full mt-2 block border-0 ring-1 ring-gray-200 rounded-md' %>
  </div>
  <div class='col-span-full'>
    <%= f.submit submit_text, class: 'px-3 py-1.5 bg-indigo-600 text-white rounded-md' %>
    <%= link_to 'Cancel', cancel_path, class: 'ml-4' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1 class='text-2xl font-bold'>Editing note</h1>

<div class='mt-6'>
  <%= render 'form', submit_text: 'Woohoo, update!', cancel_path: @note %>
</div>

app/views/notes/index.html.erb
<header>
  <%= link_to root_path, class: 'text-gray-400' do %>
    &larr; Home
  <% end %>
  <div class='flex justify-between items-center'>
    <h1 class='text-2xl font-bold'>Notes</h1>
    <%= link_to 'New Note', new_note_path, class: 'inline-block px-3 py-1.5 bg-indigo-600 rounded-md text-white' %>
  </div>
</header>

<table class='table-auto w-full my-6'>
  <thead class='text-left'>
    <tr>
      <th class='py-4 pl-3'>ID</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan='2'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr class='border-t border-gray-200'>
        <td class='py-3 px-3'><%= note.id %></td>
        <td class='px-3'><%= link_to note.title, note %></td>
        <td class='px-3'><%= note.body %></td>
        <td class='px-3'><%= link_to 'Edit', edit_note_path(note), class: 'px-3 py-1.5 border border-gray-200 rounded-md' %></td>
        <td><%= button_to 'Delete', note, method: :delete, class: 'px-3 py-1.5 bg-rose-100 text-rose-400 rounded-md' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<h1 class='text-2xl font-bold'>New note</h1>

<div class='mt-4'>
  <%= render 'form', submit_text: 'Let me note this!', cancel_path: notes_path %>
</div>

app/views/notes/show.html.erb
<header>
  <%= link_to notes_path, class: 'text-gray-400' do %>
    &larr; Back
  <% end %>
  <div class='flex justify-between items-center'>
    <h1 class='text-2xl font-bold'><%= @note.title %></h1>
    <%= link_to 'Edit note', edit_note_path(@note), class: 'px-3 py-1.5 border border-gray-200 rounded-md' %>
  </div>
</header>

<p class='mt-4'><%= @note.body %></p>

app/views/pages/home.html.erb
<h1 class="text-2xl font-bold">Welcome to the homepage!</h1>

<div class='mt-4'>
  <%= link_to 'Items', items_path, class: 'px-3 py-1.5 bg-indigo-600 text-white rounded-md' %>
  <%= link_to 'Notes', notes_path, class: 'ml-4 px-3 py-1.5 text-indigo-600 bg-indigo-100 rounded-md' %>
</div>